#This file stores configuration options for AngelicaShaders, such as the currently active shaderpack
#Wed Sep 02 10:55:18 IST 2026
allowUnknownShaders=false
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=BountifulStarsALPHA0.0.3.zip
