#This file stores configuration options for AngelicaShaders, such as the currently active shaderpack
#Mon Aug 31 01:46:58 IST 2026
allowUnknownShaders=false
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=BountifulStarsALPHA0.0.3.zip
